# Setup
title:               Learning curve
tagline:             'An authentic pursuit to rid the imposter in me 🧘'
description:         'A learning journal. Figuring things out - ML, OMSCS, hobbies, whatever currently has attention. Feynman-ish: if I cannot explain it clearly, I probably do not understand it yet. By <a href="https://twitter.com/nishzsche" target="_blank">@nishzsche</a>'
url:                 https://nishzsche.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Nishanth R
  url:               https://twitter.com/nishzsche
  email:             nishanthrajamani@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
