# .github/workflows/custom-workflow.yml
name: staging-for-tests

on:
  workflow_run:
    workflows: ["convert-notebooks-to-markdown"]
    types: [completed]
    branches: [dev]

jobs:
  custom-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --local user.name  "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge origin/dev into gh-pages
        run: |
          git merge --no-ff origin/dev

      - name: Push gh-pages
        run: git push origin gh-pages